# ===========================
#  Prompt Configuration
# ===========================
format = """[\
$username\
$hostname\
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$golang\
$lua\
$nodejs\
$aws\
$gcloud\
$sudo\
$jobs\
$status\
$container\
$shell
$character](bold 246)
"""

# right_format = """
# """

continuation_prompt = 'â–¶â–¶ '

# ===========================
#  Individual Configuration
# ===========================
[aws]
symbol = "îŒ½  "
style = "bold 246"

[buf]
symbol = "ï’ "
style = "bold 246"

[c]
symbol = "î˜ "
style = "bold 246"

[character]
success_symbol = '[â¯](bold white)'
error_symbol = '[â¯](bold white)'

[conda]
symbol = "ï„Œ "
style = "bold 246"

[dart]
symbol = "î˜ "
style = "bold 246"

[directory]
read_only = " ó°Œ¾"
truncation_length = 0
truncate_to_repo = false
style = "bold 246"

[docker_context]
symbol = "ïŒˆ "
style = "bold 246"

[elixir]
symbol = "î‰µ "
style = "bold 246"

[elm]
symbol = "î˜¬ "
style = "bold 246"

[fossil_branch]
symbol = "ï˜ "
style = "bold 246"

[git_branch]
symbol = "ï˜ "
style = "bold 067"
format = '[$symbol$branch]($style) '

[git_status]
style = 'bold 255'
format = '([$all_status$ahead_behind]($style) )'
# format = """([\
# [$conflicted](bold 174)\
# [$stashed](bold 140)\
# [$deleted](bold 235)\
# [$renamed](bold 255)\
# [$modified](bold 174)\
# [$staged](bold 180)\
# [$untracked](bold 174)\
# [$ahead_behind](bold 255)\
# ]($style) )"""

[golang]
symbol = "î˜§ "
style = "bold 246"

[guix_shell]
symbol = "ïŒ¥ "
style = "bold 246"

[haskell]
symbol = "î· "
style = "bold 246"

[haxe]
symbol = "âŒ˜ "
style = "bold 246"

[hg_branch]
symbol = "ï˜ "
style = "bold 246"

[hostname]
ssh_symbol = "î¬ "
ssh_only = false
style = "bold 144"
format = '[$hostname]($style) '
# style_user = "bold dimmed blue"

[java]
symbol = "î‰– "
style = "bold 246"

[jobs]
style = "bold dimmed 136"

[julia]
symbol = "î˜¤ "
style = "bold 246"

[lua]
symbol = "î˜  "
style = "bold 246"

[memory_usage]
symbol = "ó°› "
style = "bold 246"

[meson]
symbol = "ó°”· "
style = "bold 246"

[nim]
symbol = "ó°†¥ "
style = "bold 246"

[nix_shell]
symbol = "ïŒ“ "
style = "bold 246"

[nodejs]
symbol = "îœ˜ "
style = "bold 246"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
symbol = "ó°— "
style = "bold 246"

[pijul_channel]
symbol = "ğŸªº "
style = "bold 246"

[python]
symbol = "îˆµ "
style = "bold 246"

[rlang]
symbol = "ó°Ÿ” "
style = "bold 246"

[ruby]
symbol = "î‘ "
style = "bold 246"

[rust]
symbol = "î¨ "
style = "bold 246"

[scala]
symbol = "îœ· "
style = "bold 246"

[spack]
symbol = "ğŸ…¢ "
style = "bold 246"

[time]
disabled = false
# time_format = "%R" # Hour:Minute Format
style = "bold 246"
format = '[\($time\)]($style) '

[username]
show_always = true
style_user = "bold 144"
format = '[$user@]($style)'
